---
version: 2.1

executors:
  dev-env:
    environment:
      DOCKER_TOOLS_TEMP_IMAGE: simonsdave/clair-cicd-tools:bindle
      DOCKER_DATABASE_TEMP_IMAGE: simonsdave/clair-cicd-database:bindle
    docker:
      - image: simonsdave/bionic-dev-env:v0.6.2

jobs:
  build_test_and_deploy:
    working_directory: ~/repo
    executor: dev-env
    steps:
      - checkout
      - run: check-consistent-dev-env-version.sh --verbose
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install Python prerequisites
          command: pip3 install --requirement requirements.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Lint Python Files
          command: run-flake8.sh
      - run:
          name: PyCQA/bandit
          command: run-bandit.sh
      - run:
          name: Lint Shell Scripts
          command: run-shelllint.sh
      - run:
          name: Lint YAML Files
          command: run-yamllint.sh
      - run:
          name: Scan repo for passwords, private keys, etc.
          command: run-repo-security-scanner.sh
      - run:
          name: Run unit tests
          command: run-unit-tests.sh
      - run:
          name: Upload Unit Test Coverage Data to Codecov
          command: codecov
      - run:
          name: Build python packages
          command: build-python-package.sh
      - setup_remote_docker
      - run:
          name: Build Docker Images
          command: |
            ./dockerfiles/cicd-tools/build-docker-image.sh "dist/clair-cicd-$(python-version.sh).tar.gz" "${DOCKER_TOOLS_TEMP_IMAGE}"
            ./dockerfiles/database/build-docker-image.sh "${DOCKER_DATABASE_TEMP_IMAGE}"

workflows:
  build_test_and_deploy:
    jobs:
      - build_test_and_deploy:
          context: clair-cicd
